global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - /etc/prometheus/alerts.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]
scrape_configs:
  - job_name: baton-cal
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [app:8081]
  - job_name: baton-cal-readiness
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: [http://app:8081/actuator/health/readiness]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
