spring:
  ssl:
    bundle:
      pem:
        cal:
          reload-on-update: ${BATON_CAL_TLS_RELOAD_ON_UPDATE:true}
          keystore:
            certificate: ${BATON_CAL_TLS_CERTIFICATE}
            private-key: ${BATON_CAL_TLS_PRIVATE_KEY}

server:
  ssl:
    enabled: true
    bundle: cal

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
    ssl:
      enabled: false
